#ifndef VERSION_H_INCLUDED
#define VERSION_H_INCLUDED

	#define GITORIUM_VER_STATUS "dev"

	#define GITORIUM_VER_MAJOR "0"
	#define GITORIUM_VER_MINOR "0"

	#define GITORIUM_VER_FULL GITORIUM_VER_MAJOR"."GITORIUM_VER_MINOR"-"GITORIUM_VER_STATUS


#endif //VERSION_H_INCLUDED
