.TH GITORIUM-HOOKS 1 "January 6, 2013" "Gitorium" "Gitorium Manual"
.SH NAME
gitorium-hook-update, gitorium-hook-post-update \- Git hooks
.SH SYNOPSIS
.sp
\fBgitorium-hook-update
.br
\fBgitorium-hook-post-update
.sp
.SH DESCRIPTION
.sp
These hooks run at the specified time in the git push/pull model. These
hooks will look into the repository configuration
(gitorium-admin.git/gitorium.conf) for a list of program or scripts to
run. They are run in the order they are defined, and exit (nonzero) as
soon as one returns a nonzero value. 
.sp
.SH "SEE ALSO"
.BR gitorium-hook-admin (1),
.BR githooks (5)
