#ifndef SPECIFIC_H_INCLUDED
#define SPECIFIC_H_INCLUDED

#cmakedefine CMAKE_INSTALL_PREFIX "@CMAKE_INSTALL_PREFIX@"

#define ADMIN_REPO "gitorium-admin.git"

#define GITORIUM_VERSION "1.2-dev"

#endif // SPECIFIC_H_INCLUDED
