#ifndef VERSION_H_INCLUDED
#define VERSION_H_INCLUDED

	#define GITORIUM_VERSION_MAJOR "0"
	#define GITORIUM_VERSION_MINOR "0"
	#define GITORIUM_VERSION_REVISION "0"

	#define GITORIUM_VERSION_FULL GITORIUM_VERSION_MAJOR"."GITORIUM_VERSION_MINOR"-"GITORIUM_VERSION_REVISION


#endif //VERSION_H_INCLUDED
